---
- name: 'install syncthing'
  command: go get -u github.com/slackhq/go-audit
  environment:
    GOPATH: /opt/go/
  args:
    creates: /opt/go/src/github.com/slackhq/go-audit

- name: 'make synthing'
  command: make
  environment:
    PATH: /opt/go/bin/:{{ ansible_env.PATH }}
    GOPATH: /opt/go/
  args:
    chdir: /opt/go/src/github.com/slackhq/go-audit
    creates: /opt/go/bin/go-audit

- name: 'config for go-audit'
  copy: src=go-audit.yml dest=/etc/go-audit.yml
  notify:
    - restart go-audit

- name: 'upstart for go-audit'
  copy: src=go-audit.conf dest=/etc/init/go-audit.conf

- name: 'start go-audit'
  service: name=go-audit state=started



