---
- name: add repofile
  copy:
    src: rsyslog8.repo
    dest: /etc/yum.repos.d/rsyslog8.repo

- name: update rsyslog to v8.23
  yum: name=rsyslog-8.23.0 state=present exclude=libksi1
      enablerepo=rsyslog-v8-stable disablerepo=amzn-main

- name: rsyslog.conf
  notify:
    - restart rsyslog
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf

